// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJpWy364VGXgK38KaXXFfx6GrJodxFwdQ',
    appId: '1:22436447167:web:ff473db705d587c744570a',
    messagingSenderId: '22436447167',
    projectId: 'endernote-71c5f',
    authDomain: 'endernote-71c5f.firebaseapp.com',
    storageBucket: 'endernote-71c5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGsT_Aig6sDZgmZSeDFE1fryQGZNCh8_Q',
    appId: '1:22436447167:android:39bc0a5035dce55744570a',
    messagingSenderId: '22436447167',
    projectId: 'endernote-71c5f',
    storageBucket: 'endernote-71c5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkTKThao63FciAu5Wmpu8Z7tzZNux8D7I',
    appId: '1:22436447167:ios:cc0010379de154bc44570a',
    messagingSenderId: '22436447167',
    projectId: 'endernote-71c5f',
    storageBucket: 'endernote-71c5f.firebasestorage.app',
    iosBundleId: 'com.example.endernoteFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkTKThao63FciAu5Wmpu8Z7tzZNux8D7I',
    appId: '1:22436447167:ios:9f69753be9ccc9cd44570a',
    messagingSenderId: '22436447167',
    projectId: 'endernote-71c5f',
    storageBucket: 'endernote-71c5f.firebasestorage.app',
    iosBundleId: 'com.shaaanuu.endernote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJpWy364VGXgK38KaXXFfx6GrJodxFwdQ',
    appId: '1:22436447167:web:9be2af8abfdcd0a044570a',
    messagingSenderId: '22436447167',
    projectId: 'endernote-71c5f',
    authDomain: 'endernote-71c5f.firebaseapp.com',
    storageBucket: 'endernote-71c5f.firebasestorage.app',
  );
}
